### ISSUE TITLE
잘못된 링크를 하나 발견했습니다.

### ISSUE THREAD

**Issue by bactoria** [jojoldu/aws-lambda-telegram-travisci#1]
안녕하세요.

텔레그램 이용중에 링크가 잘못된 것을 하나 발견하였습니다.

**레이니스트(뱅크샐러드) 인턴** 링크가 잘못되었네요.

![default](https://user-images.githubusercontent.com/25674959/41359080-aea78ec6-6f64-11e8-9eab-c50793524a31.PNG)

좋은 컨텐츠 만들여주셔서 감사합니다

**Comment by jojoldu** [comment]
앗 캡쳐가 잘못된것 같습니다 수정하겠습니다! 
감사합니다 :)

**Comment by jojoldu** [comment]
@bactoria 안녕하세요! 내용 수정하였습니다.
제보 감사합니다! :)
